name: Fetch IP Lists

on:
  schedule:
    # Запускается каждый день в полночь UTC
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install BeautifulSoup4 and requests
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Fetch IPv4 and IPv6Lists
        run: python fetch_ips.py

      - name: Commit changes
        run: |
          git config --global user.name 'strikysha'
          git config --global user.email 'your-github-email'
          git add .
          git commit -m "Update IP lists" || echo "No changes to commit"
          git push
