name: Fetch IP Lists

on:
  schedule:
    # Запускается каждый день в полночь UTC
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch: # Добавляем эту строку для ручного запуска

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install BeautifulSoup4 and requests
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Fetch IPv4 and IPv6Lists
        run: python fetch_ips.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
